# -*- coding: utf-8 -*-
"""BD_2023

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2rRD1vOsBm6yJ_CzlrlrEP467y3RvaX

1 - Upload manual e leitura do banco de dados
"""

# Importar bibliotecas
import pandas as pd
from google.colab import files

# Upload manual do arquivo (.xlsx)
uploaded = files.upload()

# Capturar automaticamente o nome do arquivo enviado
nome_arquivo = list(uploaded.keys())[0]

# Ler o arquivo Excel com todas as colunas como texto
df = pd.read_excel(nome_arquivo, engine="openpyxl", dtype=str)

# Ver informações básicas do banco
print(f"Número de linhas: {df.shape[0]}")
print(f"Número de colunas: {df.shape[1]}")
print("Colunas presentes:")
print(df.columns.tolist())

# Exibir as 5 primeiras linhas
df.head()

# Inspecionar se existem valores faltantes nas colunas
df.notna().sum().sort_values()

"""2 - Renomear colunas e excluir colunas desnecessárias"""

# Mapeamento de nomes originais para nomes padronizados (conforme o prompt validado)
mapeamento_colunas = {
    "CODIGO_PEDIDO": "Código do paciente",
    "DTCOLETA_PEDIDO": "Data da coleta",
    "NASCIMENTO_PACEXTERNO": "Data de nascimento",
    "SEXO_PACEXTERNO": "Sexo",
    "NOME_CIDADE": "Cidade",
    "SIGLA_UF": "Estado",
    "RESULTADO": "Resultado covid-19",
    "A1_RESHLA": "A1",
    "A2_RESHLA": "A2",
    "B1_RESHLA": "B1",
    "B2_RESHLA": "B2",
    "C1_RESHLA": "C1",
    "C2_RESHLA": "C2",
    "DQA11_RESHLA": "DQA11",
    "DQA12_RESHLA": "DQA12",
    "DQB11_RESHLA": "DQB11",
    "DQB12_RESHLA": "DQB12",
    "DPA11_RESHLA": "DPA11",
    "DPA12_RESHLA": "DPA12",
    "DPB11_RESHLA": "DPB11",
    "DPB12_RESHLA": "DPB12",
    "DRB11_RESHLA": "DRB11",
    "DRB12_RESHLA": "DRB12",
    "DRB31_RESHLA": "DRB31",
    "DRB32_RESHLA": "DRB32",
    "DRB41_RESHLA": "DRB41",
    "DRB42_RESHLA": "DRB42",
    "DRB51_RESHLA": "DRB51",
    "DRB52_RESHLA": "DRB52"
}

# Renomear colunas (somente as que existem no DataFrame)
df.rename(columns={k: v for k, v in mapeamento_colunas.items() if k in df.columns}, inplace=True)

# Excluir colunas que devem ser descartadas (caso existam no DataFrame)
colunas_para_excluir = ["CT_I", "CT_N", "CT_ORF1AB", "QTDE_HLA", "QTDE_HLA_EXTERNO"]
df.drop(columns=[col for col in colunas_para_excluir if col in df.columns], inplace=True)

# Exibir as primeiras colunas para confirmar renomeação
print("Colunas após renomeação e exclusão:")
print(df.columns.tolist())
df.head()

"""3 - Inspeção de Hífen, Não testado e variações"""

import pandas as pd

# INSPEÇÃO DE VALORES A SEREM SUBSTITUÍDOS

# Colunas HLA
colunas_hla = [
    'A1', 'A2', 'B1', 'B2', 'C1', 'C2',
    'DQA11', 'DQA12', 'DQB11', 'DQB12',
    'DPA11', 'DPA12', 'DPB11', 'DPB12',
    'DRB11', 'DRB12', 'DRB31', 'DRB32',
    'DRB41', 'DRB42', 'DRB51', 'DRB52'
]

# Valores exatos a serem substituídos
valores_a_substituir = {
    "nao testado", "não testado", "nÃ£o testado", "nÃo testado",
    "nÃƒo testado", "nÃƒO TESTADO", "NÃ£O TESTADO", "nãO testado",
    "Nao Testado", "NÃ£o Testado", "NÃƒO TESTADO", "NT:NT", "NT:-", "-"
}

# Lista para armazenar substituições
substituicoes = []

# Verificar e registrar as substituições necessárias
for col in colunas_hla:
    for idx in df.index:
        valor = df.at[idx, col]
        if pd.notna(valor) and str(valor).strip() in valores_a_substituir:
            substituicoes.append({
                "Código do paciente": df.at[idx, "Código do paciente"],
                "Coluna": col,
                "Valor substituído": valor
            })

# Mostrar resumo da inspeção
df_auditoria = pd.DataFrame(substituicoes)
print(f"🔍 Substituições identificadas: {len(df_auditoria)}")
if not df_auditoria.empty:
    display(df_auditoria.head(10))  # Mostra primeiras substituições

"""4 - Substituição de hífen (-), Não Testado e suas variações por vazio"""

# SUBSTITUIÇÃO DOS VALORES

# Aplicar substituições seguras (sem alterar outras células)
for sub in substituicoes:
    idx = df[df["Código do paciente"] == sub["Código do paciente"]].index
    for i in idx:
        if df.at[i, sub["Coluna"]] == sub["Valor substituído"]:
            df.at[i, sub["Coluna"]] = ""

print(f"✅ Substituições aplicadas com sucesso.")

"""5 - Padronização da variável sexo"""

# Limpar e padronizar valores da coluna "Sexo"
df["Sexo"] = (
    df["Sexo"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        "feminino": "Feminino",
        "fem": "Feminino",
        "f": "Feminino",
        "masculino": "Masculino",
        "masc": "Masculino",
        "m": "Masculino"
    })
)

# Verificar valores únicos após padronização textual
print("Valores únicos após limpeza textual:")
print(df["Sexo"].unique())

# Remover linhas com valores inválidos
df = df[df["Sexo"].isin(["Feminino", "Masculino"])]

# Checar resultado final
print("Valores finais após padronização numérica:")
print(df["Sexo"].unique())
df.head()

"""6 - Exclusão de linhas com informações ausentes em data de nascimento e/ou data da coleta"""

import pandas as pd
import numpy as np

# Ajuste a leitura do seu arquivo real
# df = pd.read_excel("seu_arquivo.xlsx", keep_default_na=True)

colunas_bloco1 = ["Data da coleta", "Data de nascimento"]

# Padronizar: converter para string, tirar espaços e transformar strings vazias e similares em NaN
for col in colunas_bloco1:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace(['', 'nan', 'NaT', 'None'], np.nan)

# Filtro: linhas onde qualquer uma dessas duas colunas está vazia (NaN)
filtro_bloco1 = df[colunas_bloco1].isna().any(axis=1)

# Separar excluídos e mantidos
excluidos_bloco1 = df[filtro_bloco1].copy()
df = df[~filtro_bloco1].copy()  # atualizar df mantendo só linhas válidas

print("🔹 Excluindo linhas com data de nascimento ou data da coleta vazias")
print(f"🗑️ Total excluídos: {excluidos_bloco1.shape[0]}")
print(f"✅ Total restantes: {df.shape[0]}")
print("\n🔍 Exemplos excluídos:")
display(excluidos_bloco1.head(5))

"""7 - Inspecionar se há linhas com dados ausentes em data de nascimento e/ou data da coleta"""

# Verificar se ainda existem valores vazios/nulos nas colunas após filtragem
faltantes_apos_filtro = df[colunas_bloco1].isna().sum()

print("🔍 Valores ausentes restantes por coluna após filtro:")
print(faltantes_apos_filtro)

# Mostrar exemplos de linhas que ainda possuam valores ausentes, caso existam
linhas_com_faltantes = df[df[colunas_bloco1].isna().any(axis=1)]

if not linhas_com_faltantes.empty:
    print("\n⚠️ Atenção: Existem linhas com valores ausentes após filtro:")
    display(linhas_com_faltantes.head(5))
else:
    print("\n✅ Nenhuma linha com valores ausentes nessas colunas após o filtro.")

"""8 - Exclusão de linhas com informações ausentes em sexo e/ou cidade"""

import pandas as pd
import numpy as np

# Supondo que seu DataFrame 'df' já está carregado

colunas_bloco2 = ["Sexo", "Cidade"]

# Padronizar e substituir valores "vazios" por NaN, mantendo letras como estão
for col in colunas_bloco2:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace(
        to_replace=r'^(|nan|Nan|NAN|none|None|NONE|na|NA|n/a|N/A|nao informado|Nao Informado|NAO INFORMADO|sem dados|Sem Dados|SEM DADOS)$',
        value=np.nan,
        regex=True
    )

# Criar filtro para linhas com pelo menos uma dessas colunas vazia
filtro_bloco2 = df[colunas_bloco2].isna().any(axis=1)

# Excluir essas linhas do DataFrame
df = df[~filtro_bloco2].copy()

print("🔹 Linhas com dado ausente em 'Sexo' ou 'Cidade' excluídas.")
print(f"✅ Total de registros restantes: {df.shape[0]}")

"""9 - Inspecionar se há linhas com dados ausentes em sexo e ou cidade"""

# Verificar valores ausentes nas colunas Sexo e Cidade
faltantes = df[colunas_bloco2].isna().sum()

print("🔍 Valores ausentes por coluna:")
print(faltantes)

linhas_com_faltantes = df[df[colunas_bloco2].isna().any(axis=1)]

if not linhas_com_faltantes.empty:
    print("\n⚠️ Atenção: existem linhas com dados ausentes:")
    display(linhas_com_faltantes.head(5))
else:
    print("\n✅ Nenhuma linha com dados ausentes em 'Sexo' ou 'Cidade'.")

"""10 - Exclusão de linhas com informações ausentes ou inválidas em resultado covid"""

# Total de linhas antes da limpeza
total_antes = len(df)

# Remover linhas onde 'Resultado covid-19' está nulo
df = df[~df['Resultado covid-19'].isna()]

# Remover linhas com valor 'inconclusivo' (ignorando maiúsculas/minúsculas)
df = df[df['Resultado covid-19'].str.strip().str.lower() != 'inconclusivo']

# Remover linhas com string vazia (após tirar espaços)
df = df[df['Resultado covid-19'].str.strip() != '']

# Total de linhas após limpeza
total_apos = len(df)

print(f"Linhas antes da limpeza: {total_antes}")
print(f"Linhas após a limpeza: {total_apos}")

"""11 - Inspecionar se há linhas com dados ausentes ou "inconclusivo" em resultado covid

"""

# Verificar se ainda existem linhas vazias ou com 'inconclusivo'
restantes = df[
    (df["Resultado covid-19"].str.strip() == "") |
    (df["Resultado covid-19"].str.strip().str.lower() == "inconclusivo")
]

if len(restantes) > 0:
    print(f"⚠️ Ainda existem {len(restantes)} linhas com valor vazio ou 'inconclusivo'")
    print(restantes)
else:
    print("✅ Não há mais valores vazios ou 'inconclusivo' na coluna Resultado covid-19")

"""12 - Exclusão de registros com todas as colunas HLA vazias"""

# Lista das colunas HLA
colunas_hla = [
    "A1", "A2", "B1", "B2", "C1", "C2",
    "DQA11", "DQA12", "DQB11", "DQB12",
    "DPA11", "DPA12", "DPB11", "DPB12",
    "DRB11", "DRB12", "DRB31", "DRB32",
    "DRB41", "DRB42", "DRB51", "DRB52"
]

# Garantir que os valores sejam strings limpas, substituir NaN por string vazia
df[colunas_hla] = df[colunas_hla].astype(str).apply(lambda x: x.str.strip())
df[colunas_hla] = df[colunas_hla].replace(['nan', 'NaN', 'None', 'none', '', ' '], '')

# Total de linhas antes da exclusão
total_antes = len(df)

# Filtrar linhas onde todas as colunas HLA estão vazias
filtro_todas_vazias = (df[colunas_hla] == '').all(axis=1)

# Excluir essas linhas
df = df[~filtro_todas_vazias].copy()

# Total de linhas após exclusão
total_apos = len(df)

print(f"Linhas antes da exclusão: {total_antes}")
print(f"Linhas após exclusão das linhas com todas as colunas HLA vazias: {total_apos}")

"""13 - Inspecionar se há linhas com todas as colunas vazias em HLA"""

# Reutilizando a lista de colunas HLA
colunas_hla = [
    "A1", "A2", "B1", "B2", "C1", "C2",
    "DQA11", "DQA12", "DQB11", "DQB12",
    "DPA11", "DPA12", "DPB11", "DPB12",
    "DRB11", "DRB12", "DRB31", "DRB32",
    "DRB41", "DRB42", "DRB51", "DRB52"
]

# Padronizar os valores nas colunas HLA (caso não tenha feito no passo anterior)
for col in colunas_hla:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace(['nan', 'NaN', 'None', 'none', '', ' '], '')

# Filtrar linhas com TODAS as colunas HLA vazias
linhas_todas_vazias = df[(df[colunas_hla] == '').all(axis=1)]

print(f"Número de linhas com todas as colunas HLA vazias: {len(linhas_todas_vazias)}")

if not linhas_todas_vazias.empty:
    print("Exemplos dessas linhas:")
    display(linhas_todas_vazias.head(5))
else:
    print("Nenhuma linha com todas as colunas HLA vazias foi encontrada.")

"""PADRONIZAÇÃO DA VARIÁVEL RESULTADO COVID-19

14 - Inspeção dos valores únicos da variável Resultado covid-19
"""

# Limpeza básica: garantir que seja texto, remover espaços, usar letras minúsculas
df['Resultado covid-19'] = df['Resultado covid-19'].astype(str).str.strip().str.lower()

# Ver os valores únicos
valores_unicos = df['Resultado covid-19'].unique()

# Ver a frequência de cada valor
frequencias = df['Resultado covid-19'].value_counts(dropna=False)

# Mostrar resultados
print("📌 Valores únicos encontrados na coluna 'Resultado covid-19':")
for valor in valores_unicos:
    print("-", valor)

print("\n📊 Frequência de cada valor:")
print(frequencias)

"""15 - Padronizar níveis da variável "Resultado covid-19"
"""

# Corrigir textos com erro de codificação manualmente

df["Resultado covid-19"] = df["Resultado covid-19"].replace({
    "nã£o detectado (ausãªncia do rna de coronavã­rus sars-cov-2)": "Não detectado",
    "detectado (presenã§a do rna de coronavã­rus sars-cov-2)": "Detectado",
})

"""16 - Filtrar apenas os resultados válidos (Detectado e Não detectado)"""

# Contar linhas antes da filtragem
antes = df.shape[0]

# Normalizar espaços e grafia para evitar erro
df["Resultado covid-19"] = df["Resultado covid-19"].astype(str).str.strip()

# Filtrar apenas "Detectado" e "Não detectado"
valores_validos = ["Detectado", "Não detectado"]
df = df[df["Resultado covid-19"].isin(valores_validos)].copy()

# Contar linhas após a filtragem
depois = df.shape[0]

# Mostrar resumo
print(f"🔸 Linhas removidas: {antes - depois}")
print(f"🔸 Total de linhas restantes: {depois}")

# Frequência absoluta e relativa (%)
print("\n📊 Frequência final de 'Resultado covid-19':")
print(df["Resultado covid-19"].value_counts(dropna=False))
print("\n📊 Frequência relativa (%):")
print(df["Resultado covid-19"].value_counts(normalize=True, dropna=False) * 100)

# Ver valores únicos restantes (confirmar limpeza)
print("\n🔍 Valores únicos restantes:")
print(df["Resultado covid-19"].unique())

"""TRATAMENTO DAS COLUNAS HLA

17 - Inspecionar e criar vetor com o nome das colunas HLA
"""

colunas_hla = [
    'A1', 'A2', 'B1', 'B2', 'C1', 'C2',
    'DQA11', 'DQA12', 'DQB11', 'DQB12',
    'DPA11', 'DPA12', 'DPB11', 'DPB12',
    'DRB11', 'DRB12', 'DRB31', 'DRB32',
    'DRB41', 'DRB42', 'DRB51', 'DRB52'
]

"""18 - Remover linhas com valores de HLA contendo apenas números inteiros"""

import re

# Função para identificar se o valor contém apenas números inteiros
def contem_apenas_inteiro(valor):
    if pd.isna(valor):
        return False
    valor = str(valor).strip()
    return bool(re.fullmatch(r"\d{1,5}", valor))

# Criar uma máscara booleana para identificar linhas com esse padrão em qualquer coluna HLA
mascara_invalida_inteiro = df[colunas_hla].applymap(contem_apenas_inteiro).any(axis=1)

# Mostrar quantas linhas serão removidas
print(f"🔍 Linhas a remover (apenas inteiros nas colunas HLA): {mascara_invalida_inteiro.sum()}")

# Aplicar a filtragem
df = df[~mascara_invalida_inteiro].copy()

# Verificar total após limpeza
print(f"✅ Total de linhas após limpeza: {df.shape[0]}")

"""19 - Inspecionar se as linhas com valores de HLA contendo apenas números inteiros foram excluídas corretamente"""

import re

# Função para verificar se o valor é apenas um número inteiro (sem letras ou símbolos)
def eh_inteiro_simples(valor):
    if pd.isna(valor):
        return False
    valor = str(valor).strip()
    return bool(re.fullmatch(r"\d{1,5}", valor))

# Inspecionar os valores únicos suspeitos em cada coluna HLA
for coluna in colunas_hla:
    suspeitos = df[coluna][df[coluna].apply(eh_inteiro_simples)].unique()
    if len(suspeitos) > 0:
        print(f"\n🔍 Valores inteiros simples ainda presentes na coluna {coluna}:")
        print(suspeitos)
    else:
        print(f"\n✅ Coluna {coluna} não contém inteiros simples.")

"""20 - Remover linhas com valores decimais (ponto ou vírgula)"""

import re
import pandas as pd

# 🔹 Função para identificar valores com números decimais (com ponto ou vírgula)
def contem_decimal(valor):
    if pd.isna(valor):
        return False
    valor = str(valor).strip()
    # Aceita espaço opcional antes/depois do separador
    return bool(re.fullmatch(r"\d+\s*[.,]\s*\d+", valor))

# 🔹 Criar máscara booleana: True se qualquer coluna HLA da linha tiver decimal
mascara_decimal = df[colunas_hla].applymap(contem_decimal).any(axis=1)

# 🔍 Mostrar quantas linhas serão removidas
print(f"🔍 Linhas a remover (com número decimal nas colunas HLA): {mascara_decimal.sum()}")

# 🔹 Aplicar a filtragem
df = df[~mascara_decimal].copy()

# ✅ Verificar total após limpeza
print(f"✅ Total de linhas após limpeza: {df.shape[0]}")

"""21 - Inspecionar se as linhas com valores de HLA contendo apenas números decimais foram excluídas corretamente"""

# Verificar coluna por coluna se ainda há valores decimais (com ou sem espaços no separador)
for col in colunas_hla:
    # Regex ajustado: aceita espaço opcional antes/depois do separador
    padrao_decimal = r'\d+\s*[.,]\s*\d+'

    # Cria uma série booleana com True para valores com decimais
    decimais_restantes = df[col].dropna().astype(str).str.contains(padrao_decimal, regex=True)

    if decimais_restantes.any():
        print(f"❌ Coluna {col} ainda contém valores decimais.")
    else:
        print(f"✅ Coluna {col} não contém valores decimais.")

"""22 - Remover linhas com valores contendo barra “/” nas colunas HLA"""

# Função para verificar se o valor contém barra "/"
def contem_barra(valor):
    if pd.isna(valor):
        return False
    return "/" in str(valor)

# Criar uma máscara para identificar linhas com qualquer valor contendo "/"
mascara_invalida_barra = df[colunas_hla].applymap(contem_barra).any(axis=1)

# 📊 Mostrar quantas linhas serão removidas
print(f"🔍 Linhas a remover (contendo '/' nas colunas HLA): {mascara_invalida_barra.sum()}")

# Aplicar a filtragem
df = df[~mascara_invalida_barra].copy()

# Verificar total após limpeza
print(f"✅ Total de linhas após limpeza: {df.shape[0]}")

"""23 - Inspecionar se as linhas com valores de HLA contendo / foram excluídas corretamente


"""

# Verificação por coluna: se ainda restam valores com "/"
for coluna in colunas_hla:
    if df[coluna].astype(str).str.contains("/", na=False).any():
        print(f"❌ Coluna {coluna} ainda contém valores com '/'.")
    else:
        print(f"✅ Coluna {coluna} não contém valores com '/'.")

"""24 - Remover linhas com apenas letras nas colunas HLA"""

import pandas as pd
import re

# Função para verificar se o valor é composto apenas por letras (A-Z ou a-z)
def apenas_letras(valor):
    if pd.isna(valor):
        return False
    valor_str = str(valor).strip()
    return valor_str.isalpha()

# Aplicar a função em todas as colunas HLA
mascara_letras_invalidas = df[colunas_hla].applymap(apenas_letras).any(axis=1)

# Mostrar quantas linhas serão removidas
print(f"🔍 Linhas a remover (valores com apenas letras): {mascara_letras_invalidas.sum()}")

# Remover essas linhas
df = df[~mascara_letras_invalidas].copy()

# Mostrar total de linhas restantes
print(f"✅ Total de linhas após remoção: {df.shape[0]}")

"""25 - Inspecionar se as linhas com valores de HLA contendo contendo só letras foram excluídas corretamente"""

# Função para verificar se o valor é composto apenas por letras
def verificar_apenas_letras(valor):
    if pd.isna(valor):
        return False
    valor_str = str(valor).strip()
    return valor_str.isalpha()

# Verificar e reportar por coluna
for coluna in colunas_hla:
    tem_valores = df[coluna].apply(verificar_apenas_letras).any()
    if tem_valores:
        print(f"❌ Coluna {coluna} ainda contém valores com apenas letras.")
    else:
        print(f"✅ Coluna {coluna} está limpa (sem valores compostos apenas por letras).")

"""26 - Remover o * e as letras à esquerda das colunas HLA"""

# 🧠 Função para remover o "*" e tudo antes dele
def remover_prefixo_asterisco(valor):
    if pd.isna(valor):
        return valor  # manter valores ausentes
    valor = str(valor)
    if "*" in valor:
        return valor.split("*", 1)[1]
    return valor  # manter como está se não tiver "*"

# Contadores e exemplos
total_corrigidos = 0
exemplos = []

# 🔁 Aplicar em todas as colunas HLA
for coluna in colunas_hla:
    antes = df[coluna].astype(str)  # valores originais como string
    depois = antes.apply(remover_prefixo_asterisco)

    # Identificar quais mudaram
    alterados = antes != depois
    total_corrigidos += alterados.sum()

    # Guardar até 5 exemplos dessa coluna
    exemplos_coluna = list(zip(antes[alterados].head(5), depois[alterados].head(5)))
    exemplos.extend([(coluna, orig, novo) for orig, novo in exemplos_coluna])

    # Substituir no dataframe
    df[coluna] = depois

print(f"✅ Asterisco e prefixos removidos com sucesso.")
print(f"🔍 Total de observações corrigidas: {total_corrigidos}")

if exemplos:
    print("\n📌 Exemplos de correções:")
    for col, orig, novo in exemplos[:10]:  # até 10 exemplos no total
        print(f"  - Coluna {col}: '{orig}' → '{novo}'")

"""27 - Inspecionar se o * e as letras à esquerda das colunas HLA foram removidos corretamente"""

# Dicionário para armazenar contagens
contagem_asterisco = {}

# Verificar presença de "*" em cada coluna
for coluna in colunas_hla:
    contagem = df[coluna].astype(str).str.contains(r"\*", na=False).sum()
    contagem_asterisco[coluna] = contagem

# Exibir resultados
print("🔍 Verificação de presença do caractere '*' nas colunas HLA:\n")
for coluna, total in contagem_asterisco.items():
    print(f"- {coluna}: {total} ocorrência(s) com '*'")

# Verificação geral
total_geral = sum(contagem_asterisco.values())
if total_geral == 0:
    print("\n✅ Nenhuma ocorrência de '*' encontrada nas colunas HLA.")
else:
    print(f"\n⚠️ Ainda há {total_geral} valor(es) com '*' a serem tratados.")

"""28 - Inserir dois pontos entre números e letras (ex: 01AB → 01:AB)"""

import re
import pandas as pd

# Lista de colunas HLA
colunas_hla = [
    "A1", "A2", "B1", "B2", "C1", "C2",
    "DQA11", "DQA12", "DQB11", "DQB12",
    "DPA11", "DPA12", "DPB11", "DPB12",
    "DRB11", "DRB12", "DRB31", "DRB32",
    "DRB41", "DRB42", "DRB51", "DRB52"
]

# Lista para registrar exemplos de correção
exemplos_corrigidos = []

# 🧠 Função para corrigir valores colados (ex: 01AB → 01:AB)
def corrigir_hla(valor):
    if pd.isna(valor):
        return valor  # mantém valores ausentes

    valor_original = str(valor).strip()

    if ":" in valor_original:
        return valor_original  # já contém dois pontos, manter

    if re.fullmatch(r"[A-Za-z]+", valor_original):
        return valor_original  # apenas letras, mantém

    if re.fullmatch(r"\d+[A-Za-z]+", valor_original):
        valor_corrigido = re.sub(r"(\d+)([A-Za-z]+)", r"\1:\2", valor_original)

        # Salvar exemplo se foi alterado
        if valor_original != valor_corrigido and len(exemplos_corrigidos) < 10:
            exemplos_corrigidos.append((valor_original, valor_corrigido))

        return valor_corrigido

    return valor_original  # qualquer outro formato permanece igual

# 📊 Contar antes quantos valores colados existem
padrao_colado = r"^\d+[A-Za-z]+$"
antes = sum(df[col].astype(str).str.match(padrao_colado, na=False).sum() for col in colunas_hla)

# 🔁 Aplicar a correção e contar alterações
alteracoes = 0
for coluna in colunas_hla:
    df[coluna] = df[coluna].apply(corrigir_hla)

# Contar depois quantos valores colados ainda existem
depois = sum(df[col].astype(str).str.match(padrao_colado, na=False).sum() for col in colunas_hla)

# Calcular alterações reais
alteracoes = antes - depois

# 📢 Retornos
print(f"📊 Valores com números e letras colados ANTES: {antes}")
print(f"✅ Inserções de dois pontos realizadas: {alteracoes}")
if exemplos_corrigidos:
    print("📝 Exemplos de inserções realizadas:")
    for original, corrigido in exemplos_corrigidos:
        print(f"   {original} → {corrigido}")

"""29 - Inspecionar se existem letras e números sem os dois pontos"""

# 🔍 Identificar valores suspeitos ainda não corrigidos
valores_suspeitos = {}

for coluna in colunas_hla:
    suspeitos = df[coluna].dropna().unique()
    valores_colados = [v for v in suspeitos if re.fullmatch(r"\d+[A-Za-z]+", str(v))]
    if valores_colados:
        valores_suspeitos[coluna] = valores_colados

# 📋 Exibir resultados
if valores_suspeitos:
    print("⚠️ Valores ainda colados (sem dois pontos) encontrados:")
    for col, valores in valores_suspeitos.items():
        print(f"🔸 {col}: {valores}")
else:
    print("✅ Todos os valores colados foram corrigidos com dois pontos.")

"""30 - Exclusão de linhas com o erro "day"
"""

import pandas as pd

# Lista das colunas HLA (ajuste se precisar)
colunas_hla = [
    "A1", "A2", "B1", "B2", "C1", "C2", "DQA11", "DQA12",
    "DQB11", "DQB12", "DPA11", "DPA12", "DPB11", "DPB12",
    "DRB11", "DRB12", "DRB31", "DRB32", "DRB41", "DRB42",
    "DRB51", "DRB52"
]

# Filtra as colunas HLA presentes no df
colunas_hla_presentes = [col for col in colunas_hla if col in df.columns]

total_antes = df.shape[0]

def contem_day_e_virgula(valor):
    if pd.isna(valor):
        return False
    valor = str(valor).lower()
    return ("day" in valor) and ("," in valor)

# Máscara para exclusão (qualquer célula com 'day' e ',')
mask_day_virgula = df[colunas_hla_presentes].applymap(contem_day_e_virgula).any(axis=1)

# Separar linhas excluídas
excluidos_day = df[mask_day_virgula].copy()

# Atualizar df removendo essas linhas
df = df[~mask_day_virgula].copy()

total_depois = df.shape[0]

print(f"🔹 Antes da exclusão (day + vírgula): {total_antes}")
print(f"🗑️ Excluídos (day + vírgula): {excluidos_day.shape[0]}")
print(f"✅ Restantes após exclusão (day + vírgula): {total_depois}")

print("\n🔍 Exemplos de exclusão (day + vírgula):")
display(excluidos_day.head(5))

"""31 - Inspecionar se todos as linhas com erros "day" foram excluídas"""

# Verificar se ainda existem observações com "day" e "," nas colunas HLA
mask_restante = df[colunas_hla_presentes].applymap(
    lambda x: (isinstance(x, str) and ("day" in x.lower()) and ("," in x))
).any(axis=1)

total_restantes = mask_restante.sum()

print(f"🔎 Total de linhas com 'day' e ',' ainda presentes: {total_restantes}")

# Mostrar alguns exemplos (até 5 linhas)
if total_restantes > 0:
    print("\n📋 Exemplos dessas linhas:")
    display(df.loc[mask_restante, colunas_hla_presentes].head(5))
else:
    print("✅ Nenhuma observação com 'day' e ',' encontrada.")

"""32 - Inspecionar quantas observações terminam com ":00"
"""

import pandas as pd

# Lista de colunas HLA
colunas_hla = [
    "A1", "A2", "B1", "B2", "C1", "C2",
    "DQA11", "DQA12", "DQB11", "DQB12",
    "DPA11", "DPA12", "DPB11", "DPB12",
    "DRB11", "DRB12", "DRB31", "DRB32",
    "DRB41", "DRB42", "DRB51", "DRB52"
]

# 📌 Quantidade total de linhas
total_linhas = len(df)

# 📌 Função para verificar se o último campo é igual a "00"
def termina_com_00(valor):
    if pd.isna(valor):  # Ignorar valores ausentes
        return False
    valor_str = str(valor).strip()
    if ":" in valor_str:
        partes = valor_str.split(":")
        return partes[-1] == "00"
    return False

# 📌 Máscara booleana por célula (somente nas colunas HLA)
mascara_00 = df[colunas_hla].applymap(termina_com_00)

# 📌 Quantidade de linhas que possuem pelo menos 1 valor terminando com ":00"
linhas_com_00 = mascara_00.any(axis=1).sum()

# 📌 Quantidade total de células com final ":00"
observacoes_com_00 = mascara_00.sum().sum()

# 📌 Linhas de exemplo (primeiras 5)
exemplos = df[mascara_00.any(axis=1)].head()

# 📌 Retorno no console
print(f"📊 Total de linhas no DataFrame: {total_linhas}")
print(f"📊 Linhas com pelo menos uma coluna HLA terminando com ':00': {linhas_com_00}")
print(f"📊 Total de observações (células) terminando com ':00': {observacoes_com_00}")
print("\n🔍 Exemplos de linhas com valores terminando com ':00':")
print(exemplos)

"""CÓDIGO ESPECIAL: manter no banco somente linhas com final :00 para conferência no software R"""

import pandas as pd

# Lista de colunas HLA
colunas_hla = [
    "A1", "A2", "B1", "B2", "C1", "C2",
    "DQA11", "DQA12", "DQB11", "DQB12",
    "DPA11", "DPA12", "DPB11", "DPB12",
    "DRB11", "DRB12", "DRB31", "DRB32",
    "DRB41", "DRB42", "DRB51", "DRB52"
]

# 🔹 Contar total de linhas antes
total_antes = len(df)

# Função para verificar se valor termina com ":00" (último campo)
def termina_com_00(valor):
    if pd.isna(valor):  # Ignorar valores vazios
        return False
    valor_str = str(valor).strip()
    if ":" in valor_str:
        partes = valor_str.split(":")
        return partes[-1] == "00"
    return False

# Criar máscara para identificar linhas com pelo menos um ":00"
mascara_00 = df[colunas_hla].applymap(termina_com_00).any(axis=1)

# Filtrar o dataframe mantendo somente linhas que satisfazem a condição
df = df[mascara_00].copy()

# 🔹 Contar total de linhas depois
total_depois = len(df)

# Mostrar exemplo das linhas mantidas
print(f"📊 Total de linhas antes do filtro: {total_antes}")
print(f"📊 Total de linhas mantidas (com pelo menos um ':00'): {total_depois}")
print("\n🔍 Exemplos das linhas mantidas:")
print(df.head())

"""33 - Excluir "oo" do final"""

import pandas as pd

# Lista de colunas HLA
colunas_hla = [
    "A1", "A2", "B1", "B2", "C1", "C2",
    "DQA11", "DQA12", "DQB11", "DQB12",
    "DPA11", "DPA12", "DPB11", "DPB12",
    "DRB11", "DRB12", "DRB31", "DRB32",
    "DRB41", "DRB42", "DRB51", "DRB52"
]

# Função para remover ":00" apenas se estiver no final
def remover_final_00(valor):
    if isinstance(valor, str) and valor.endswith(":00"):
        return valor[:-3]  # remove ":00"
    return valor

# Lista para armazenar exemplos
exemplos = []

# Contador de correções
corrigidas = 0

# Aplica a função em todas as colunas HLA
for col in colunas_hla:
    if col in df.columns:
        for idx, valor in df[col].items():
            novo_valor = remover_final_00(valor)
            if valor != novo_valor:
                corrigidas += 1
                if len(exemplos) < 15:  # guarda até 15 exemplos
                    exemplos.append({
                        "Linha": idx,
                        "Coluna": col,
                        "Antes": valor,
                        "Depois": novo_valor
                    })
                df.at[idx, col] = novo_valor

# Número total de linhas no banco
total_linhas = len(df)

print(f"✅ Total de observações corrigidas: {corrigidas}")
print(f"📊 Total de linhas no banco: {total_linhas}\n")

print("🔎 Exemplos de correções realizadas (até 15):")
for ex in exemplos:
    print(f"Linha {ex['Linha']} | Coluna {ex['Coluna']} | Antes: {ex['Antes']} | Depois: {ex['Depois']}")

"""34 - Inspecionar se todas as observações com final ":00" foram corrigidas corretamente"""

# Verificação se ainda existe algum valor terminando em ":00" nas colunas HLA
problemas = []

for col in colunas_hla:
    if col in df.columns:
        linhas_com_problema = df[df[col].astype(str).str.endswith(":00")].index.tolist()
        for idx in linhas_com_problema:
            problemas.append({
                "Linha": idx,
                "Coluna": col,
                "Valor": df.at[idx, col]
            })

if problemas:
    print(f"⚠️ Foram encontradas {len(problemas)} observações ainda com ':00' no final.\n")
    print("🔎 Exemplos (até 15):")
    for ex in problemas[:15]:
        print(f"Linha {ex['Linha']} | Coluna {ex['Coluna']} | Valor: {ex['Valor']}")
else:
    print("✅ Nenhuma observação com ':00' no final foi encontrada nas colunas HLA!")

"""TRATAMENTO DAS DUPLICATAS

35 - Inspecionar quantas duplicatas existem no banco
"""

import pandas as pd

# Contagem de quantas vezes cada paciente aparece
duplicatas = df['Código do paciente'].value_counts()

# Exibir quantos pacientes aparecem mais de 1 vez
print("Total de pacientes duplicados:", (duplicatas > 1).sum())

# Distribuição: quantos pacientes aparecem 2x, 3x, 4x...
distribuicao = duplicatas.value_counts().sort_index()

print("\nDistribuição das duplicatas (quantidade de vezes que cada paciente aparece):")
print(distribuicao)

# -----------------------------
# Exemplos de pacientes duplicados
# -----------------------------
# Filtrar apenas os pacientes que aparecem mais de uma vez
pacientes_duplicados = duplicatas[duplicatas > 1].index

# Selecionar algumas linhas desses pacientes duplicados (por exemplo, os 5 primeiros)
exemplos = df[df['Código do paciente'].isin(pacientes_duplicados[:5])]

# Mostrar como DataFrame (fica em formato de tabela)
exemplos_display = exemplos.sort_values(by='Código do paciente').head(20)  # até 20 linhas para visualizar
exemplos_display

"""36 - Conferência dados básicos das duplicatas"""

# Definir os campos básicos que devem ser idênticos entre duplicatas
campos_basicos = ['Data de nascimento', 'Data da coleta', 'Sexo', 'Cidade']

# Quantidade de linhas antes
linhas_antes = len(df)

# Agrupar por paciente e verificar divergências
def verificar_divergencia(grupo):
    for campo in campos_basicos:
        if grupo[campo].nunique() > 1:  # mais de 1 valor diferente
            return True  # tem divergência
    return False  # todos iguais

# Identificar pacientes com divergências
pacientes_divergentes = df.groupby('Código do paciente').filter(verificar_divergencia)['Código do paciente'].unique()

# Remover todos os pacientes divergentes
df_filtrado = df[~df['Código do paciente'].isin(pacientes_divergentes)].copy()

# Quantidade de linhas depois
linhas_depois = len(df_filtrado)

# Resultado
print("Quantidade de pacientes com divergência nos campos básicos:", len(pacientes_divergentes))
print("Quantidade de linhas antes:", linhas_antes)
print("Quantidade de linhas depois:", linhas_depois)
print("Linhas removidas:", linhas_antes - linhas_depois)

"""37 - Mesclar"""

# ------------------------------
# MESCLAGEM FINAL DOS PACIENTES
# ------------------------------

colunas_hla = [col for col in df_filtrado.columns if col.startswith(("A", "B", "C", "D"))]

conflitos_hla = []

def selecionar_hla(valores, paciente, coluna):
    valores = list(set([str(v).strip() for v in valores if str(v).strip() != ""]))  # só preenchidos

    if len(valores) == 1:
        return valores[0]

    # Função auxiliar para ranking
    def prioridade(v):
        blocos = len(v.split(":"))              # nº de blocos
        termina_letra = v[-1].isalpha()         # termina com letra
        return (blocos, termina_letra)

    # Ordenar
    ordenados = sorted(valores, key=prioridade, reverse=True)

    # Check if there are at least two elements before comparing
    if len(ordenados) >= 2 and prioridade(ordenados[0]) == prioridade(ordenados[1]):
        conflitos_hla.append({"paciente": paciente, "coluna": coluna, "valores": valores})
        return None  # sinal de que não houve consenso
    elif len(ordenados) > 0:
        return ordenados[0]
    else:
        return None


def mesclar_paciente(grupo):
    paciente_id = grupo['Código do paciente'].iloc[0]

    # Checar se há conflito em alguma coluna HLA
    conflito_local = False
    linha = grupo.iloc[0].copy()

    for col in colunas_hla:
        valor = selecionar_hla(grupo[col].dropna().astype(str).tolist(), paciente_id, col)
        if valor is None and any(pd.notna(val) and str(val).strip() != "" for val in grupo[col]): # Conflito detectado and at least one value was present
             conflito_local = True
             break
        linha[col] = valor

    if conflito_local:
        # Se houver conflito → retorna todas as linhas originais desse paciente
        return grupo
    else:
        # Caso contrário → retorna apenas a linha consolidada
        return linha.to_frame().T

# ------------------------------
# Aplicar mesclagem
# ------------------------------
df_final = df_filtrado.groupby('Código do paciente', group_keys=False).apply(mesclar_paciente).reset_index(drop=True)

print("Linhas antes da mesclagem:", len(df_filtrado))
print("Linhas depois da mesclagem:", len(df_final))
print("Total de conflitos registrados:", len(conflitos_hla))

# ------------------------------
# Exemplos antes e depois
# ------------------------------
duplicados = df_filtrado['Código do paciente'].value_counts()
pacientes_repetidos = duplicados[duplicados > 1].index[:4]

print("\n=== Exemplos de pacientes repetidos ANTES da mesclagem ===")
exemplos_antes = df_filtrado[df_filtrado['Código do paciente'].isin(pacientes_repetidos)]
display(exemplos_antes.sort_values(by='Código do paciente'))

print("\n=== Mesmos pacientes DEPOIS da mesclagem ===")
exemplos_depois = df_final[df_final['Código do paciente'].isin(pacientes_repetidos)]
display(exemplos_depois.sort_values(by='Código do paciente'))

"""38-Conferir"""

# ------------------------------
# INSPEÇÃO DE DUPLICATAS NO RESULTADO FINAL
# ------------------------------

# Contar quantas vezes cada paciente aparece
contagem_final = df_final['Código do paciente'].value_counts()

# Pacientes que ainda estão duplicados
pacientes_duplicados_final = contagem_final[contagem_final > 1]

print("Total de pacientes com mais de uma linha no resultado final:", len(pacientes_duplicados_final))

if len(pacientes_duplicados_final) > 0:
    print("\nDistribuição das duplicatas no resultado final (quantas vezes aparecem):")
    print(pacientes_duplicados_final.value_counts().sort_index())

    # Mostrar exemplos (até 5 pacientes)
    exemplos_final = df_final[df_final['Código do paciente'].isin(pacientes_duplicados_final.index[:5])]
    print("\nExemplos de duplicatas ainda presentes no resultado final:")
    display(exemplos_final.sort_values(by='Código do paciente'))

"""39 - Excluir duplicata divergente"""

# 1. Encontrar duplicatas (todas as ocorrências)
duplicatas = df_final[df_final.duplicated(subset=["Código do paciente"], keep=False)]

print("Duplicatas encontradas (serão removidas):")
print(duplicatas)

# 2. Excluir todas as duplicatas e sobrescrever df_final
df_final = df_final[~df_final.index.isin(duplicatas.index)]

print("\nTotal de linhas removidas:", len(duplicatas))
print("Total de registros após exclusão:", len(df_final))

"""DOWNLOAD FINAL"""

# Salvar o DataFrame tratado (sem duplicatas) em Excel
df_final.to_excel("/content/banco_tratado.xlsx", index=False)

# Oferecer o download
from google.colab import files
files.download("/content/banco_tratado.xlsx")

""" 40 - DOWNLOAD PARA INSPEÇÃO MANUAL

"""

# Ver tipos de dados de todas as colunas
df.dtypes

# Exibir tipos de dados ordenados alfabeticamente
print("\n📋 Tipos de dados por coluna:")
print(df.dtypes.sort_index())

# Salvar o DataFrame em Excel
df.to_excel("/content/banco_tratado.xlsx", index=False)

# Oferecer o download
files.download("/content/banco_tratado.xlsx")
